name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.conf.name }} | ${{ matrix.cmake-build-type }}"
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:
          - name: Windows 2019
            os: windows-2019
          - name: Ubuntu 20.04
            os: ubuntu-20.04
          - name: MacOS 10.15
            os: macos-10.15
        cmake-build-type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v2

    - name: Add toolchain to path
      run: echo "$HOME/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin" >> $GITHUB_PATH

    - name: Add python to path
      run: echo "$HOME/.espressif/python_env/idf4.1_py3.8_env/bin" >> $GITHUB_PATH

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.cmake-build-type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.cmake-build-type }}
